version: '3.9'

services:
  server:
    container_name: galaxy-pizza-server-dev
    image: galaxy-pizza-server-dev
    build:
      context: .
      target: development
    ports:
      - 8888:8888
    working_dir: /app
    volumes:
      - ./:/app
    links:
      - mongo
    environment:
      PORT: 8888
      MONGODB_URI: mongodb://mongo/galaxy-pizza

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: always

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_PORT: 27017
    links:
      - mongo
